/* build.js — generate assets/js/config.js from environment variables.
 *
 * This is the entire "build". The landing page is otherwise fully static;
 * the only thing that varies per environment is the Supabase URL + anon key,
 * which must reach the client. The anon key is public by design (it is already
 * shipped in the app bundle), so writing it into a static file is expected —
 * the security is RLS (anon may INSERT into beta_signups, and the ABSENCE of a
 * SELECT policy makes it unreadable).
 *
 * Vercel runs `node build.js` (see package.json / vercel.json) with the
 * project's env vars set. Locally: SUPABASE_URL=… SUPABASE_ANON_KEY=… node build.js
 *
 * Zero dependencies on purpose — this repo shares nothing with the app.
 */
const fs = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || '';
// The Clerk signup destination is stable, but allow an override for staging.
const appSignupUrl = process.env.APP_SIGNUP_URL || 'https://ourprovisions.velayo.ai/sign-up';

const config = { supabaseUrl: url, anonKey: key, appSignupUrl: appSignupUrl };

const out =
`/* GENERATED by build.js — do not edit, do not commit.
   Populated from environment variables at build time. */
window.OP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

const dest = path.join(__dirname, 'assets', 'js', 'config.js');
fs.writeFileSync(dest, out, 'utf8');

console.log('build.js → assets/js/config.js');
console.log('  SUPABASE_URL      : ' + (url ? 'set (' + url + ')' : '*** MISSING ***'));
console.log('  SUPABASE_ANON_KEY : ' + (key ? 'set (' + key.length + ' chars)' : '*** MISSING ***'));
console.log('  APP_SIGNUP_URL    : ' + appSignupUrl);

if(!url || !key){
  // Do not fail the build — a preview without env still renders and the door
  // still opens (the insert is skipped). But make the gap loud in the log.
  console.warn('\n  ⚠  Supabase env not fully set — the page will render and the door will\n     open, but no beta_signups row will be written. Set both vars in the\n     Vercel project (Settings → Environment Variables) for a live front door.');
}
